### ISSUE TITLE
Improve Meta Tags

### ISSUE THREAD

**Issue by Karvel** [Karvel/analogjs-blog#120]
# Changes

- [x] Add description meta tags to pages without them
- [x] Use site logo as image meta tag fallback
- [x] Add keywords meta tags
  - [x] Homepage and article pages to start
- [x] Set twitter card tag at app root level
